y = m1x1 + m2x2 + m3x3 ... + b

In [29]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [30]:
df = pd.read_csv(r"D:\Data analytics projects\ML Basics\Limear Regression Multiple Variables\homeprices.csv")

In [31]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [32]:
x= df.bedrooms.median()

In [33]:
df.bedrooms.fillna(x,inplace=True)

In [34]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [35]:
reg = linear_model.LinearRegression()

In [36]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [37]:
reg.coef_ #m1,m2,m3

array([  112.06244194, 23388.88007794, -3231.71790863])

In [38]:
reg.intercept_ #b

221323.00186540408

In [39]:
reg.predict([[3000,5,20]]) #predicting for 3000 area, 3 bedrooms, 14 years age

array([609820.36990884])

# We import joblib to save this reg modal in a file that can be sent to people for predictions. 

In [43]:
import joblib

In [44]:
joblib.dump(reg,'modal')

['modal']

In [45]:
m = joblib.load('modal')

In [46]:
m.predict([[3000,5,40]])

array([545186.01173619])

In [47]:
m.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [48]:
m.intercept_

221323.00186540408